=== sedoo/sedoo-portalgenerator/extracteur/xml/requete.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema elementFormDefault="qualified" targetNamespace="http://sedoo.fr/extract/requete" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:req="http://sedoo.fr/extract/requete">
    <xsd:element name="requete" type="req:requete_Type"></xsd:element>

    <xsd:complexType name="requete_Type">
    	<xsd:sequence>
            <xsd:element name="projet" type="xsd:string" maxOccurs="1" minOccurs="1"></xsd:element>
            <xsd:element name="selection" type="req:selection_Type"
    			maxOccurs="1" minOccurs="1">
    		</xsd:element>
    		<xsd:element name="utilisateur" type="req:utilisateur_Type"
    			maxOccurs="1" minOccurs="1">
    		</xsd:element>
    		<xsd:element name="options" type="req:options_Type"
    			maxOccurs="1" minOccurs="1">
    		</xsd:element>
    	</xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="zone_Type">
    	<xsd:sequence>
    		<xsd:element name="lat_min" type="xsd:double" maxOccurs="1" minOccurs="0"></xsd:element>
    		<xsd:element name="lat_max" type="xsd:double" maxOccurs="1" minOccurs="0"></xsd:element>
    		<xsd:element name="lon_min" type="xsd:double" maxOccurs="1" minOccurs="0"></xsd:element>
    		<xsd:element name="lon_max" type="xsd:double" maxOccurs="1" minOccurs="0"></xsd:element>
    	</xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="period_Type">
    	<xsd:sequence>
    		<xsd:element name="date_min" type="xsd:dateTime" maxOccurs="1" minOccurs="0"></xsd:element>
    		<xsd:element name="date_max" type="xsd:dateTime" maxOccurs="1" minOccurs="0"></xsd:element>
    	</xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="selection_Type">
    	<xsd:sequence>
    		<xsd:element name="periode" type="req:period_Type" maxOccurs="1" minOccurs="1">
    		</xsd:element>
    		<xsd:element name="zone" type="req:zone_Type" maxOccurs="1" minOccurs="1">
    		</xsd:element>
    		<xsd:element name="datasets" type="req:datasets_Type" maxOccurs="1" minOccurs="1"></xsd:element>
    		<xsd:element name="places" type="req:places_Type" maxOccurs="1" minOccurs="1"></xsd:element>
    		<xsd:element name="variables" type="req:variables_Type" maxOccurs="1" minOccurs="1"></xsd:element>
    	</xsd:sequence>
    </xsd:complexType>


    <xsd:complexType name="datasets_Type">
    	<xsd:sequence>
    		<xsd:element name="dats_id" type="xsd:int" maxOccurs="unbounded" minOccurs="0"></xsd:element>
    	</xsd:sequence>
    </xsd:complexType>
    
    <xsd:complexType name="places_Type">
    	<xsd:sequence>
    		<xsd:element name="place_id" type="xsd:int" maxOccurs="unbounded" minOccurs="0"></xsd:element>
    	</xsd:sequence>
    </xsd:complexType>
    
    <xsd:complexType name="variables_Type">
    	<xsd:sequence>
    		<xsd:element name="var_id" type="xsd:int" maxOccurs="unbounded" minOccurs="0"></xsd:element>
    	</xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="utilisateur_Type">
    	<xsd:sequence>
    		<xsd:element name="utilisateur_email" type="xsd:string" maxOccurs="1" minOccurs="1"></xsd:element>
    		<xsd:element name="utilisateur_nom" type="xsd:string" maxOccurs="1" minOccurs="1"></xsd:element>
    		<xsd:element name="utilisateur_institute" type="xsd:string" maxOccurs="1" minOccurs="0"></xsd:element>
    	</xsd:sequence>
    </xsd:complexType>
    
    <xsd:complexType name="options_Type">
    	<xsd:sequence>
    		<xsd:element name="format" type="xsd:string" maxOccurs="1" minOccurs="1">
    		</xsd:element>
    		<xsd:element name="format_version" type="xsd:string" maxOccurs="1" minOccurs="0">
    		</xsd:element>
    		<xsd:element name="compression" type="xsd:string" maxOccurs="1" minOccurs="1">
    		</xsd:element>
    		<xsd:element name="valeurs_absentes" type="xsd:string" maxOccurs="1" minOccurs="0">
    		</xsd:element>
    		<xsd:element name="separateur" type="xsd:string" maxOccurs="1" minOccurs="0">
    		</xsd:element>
    		<xsd:element name="valeur_flag" type="xsd:boolean" maxOccurs="1" minOccurs="1"></xsd:element>
    		<xsd:element name="valeur_delta" type="xsd:boolean" maxOccurs="1" minOccurs="1"></xsd:element>
    	</xsd:sequence>
    </xsd:complexType>
</xsd:schema>

=== sedoo/sedoo-portalgenerator/input/extraction/template-catalogue-extract/src/test/resources/test_nc_timeSeries.xml
<?xml version="1.0" encoding="UTF-8"?>
<requete xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://mistrals.sedoo.fr/extract/requete" xsi:schemaLocation="http://mistrals.sedoo.fr/extract/requete http://mistrals.sedoo.fr/extract/requete.xsd">
<projet>HyMeX</projet>
  <selection>
  	<periode>
    	<date_min>2013-01-01T00:00:00</date_min>
    	<date_max>2013-09-30T23:59:59</date_max>
    </periode>
    <zone>
    	<lat_min>40</lat_min>
    	<lat_max>55</lat_max>
    	<lon_min>-15</lon_min>
    	<lon_max>30</lon_max>
    </zone>
    <datasets>
    	<!-- 495     <dats_id>592</dats_id>   595   -->
    	 <dats_id>600</dats_id>
    </datasets>    
    <places>
   		<!--place_id>16955</place_id>
    	<place_id>17829</place_id>
    	<place_id>13269</place_id>
    	<place_id>13189</place_id>
    	<place_id>6404</place_id>
    	<place_id>6417</place_id>
    	<place_id>442</place_id>
    	<place_id>10020</place_id>
    	<place_id>12897</place_id>
    	<place_id>10019</place_id>
    	<place_id>8504</place_id>
    	<place_id>8505</place_id>
    	<place_id>11067</place_id>
    	<place_id>11079</place_id>
    	<place_id>13111</place_id>
    	<place_id>13104</place_id>
    	<place_id>12904</place_id>
    	<place_id>12920</place_id>
    	<place_id>10028</place_id-->
    </places>   
  	<variables>
  		<!--var_id>332</var_id>
  		<var_id>52</var_id>
  		<var_id>336</var_id>
  		<var_id>279</var_id>
  		<var_id>205</var_id>
  		<var_id>232</var_id>
  		<var_id>513</var_id>
  		<var_id>484</var_id>
  		<var_id>729</var_id>
  		<var_id>730</var_id>
  		<var_id>731</var_id>
  		<var_id>687</var_id-->
  		<!--var_id>481</var_id>
  		<var_id>232</var_id>
  		<var_id>443</var_id>
  		<var_id>279</var_id>
  		<var_id>205</var_id>
  		<var_id>235</var_id-->
  	</variables>
  </selection>
  <utilisateur>
    <utilisateur_email>guillaume.brissebrat@obs-mip.fr</utilisateur_email>
    <utilisateur_nom>Guillaume Brissebrat</utilisateur_nom>    
    <utilisateur_institute>Sedoo</utilisateur_institute>
  </utilisateur>
  <options>
    <format>netcdf</format>
    <format_version>timeSeries</format_version>
    <compression>gzip</compression>
    <valeurs_absentes>-9999.9</valeurs_absentes>
    <separateur>;</separateur>
    <valeur_flag>true</valeur_flag>
    <valeur_delta>true</valeur_delta>
  </options>
</requete>

=== sedoo/sedoo-portalgenerator/input/extraction/template-catalogue-extract/src/test/resources/test2.xml
<?xml version="1.0" encoding="UTF-8"?>
<requete xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://mistrals.sedoo.fr/extract/requete" xsi:schemaLocation="http://mistrals.sedoo.fr/extract/requete http://mistrals.sedoo.fr/extract/requete.xsd">
<projet>HyMeX</projet>
  <selection>
  	<periode>
    	<!--date_min>1988-10-01T00:00:00</date_min>
    	<date_max>1988-10-31T23:59:00</date_max-->
    </periode>
    <zone>
    	<lat_min>20</lat_min>
    	<lat_max>50</lat_max>
    	<lon_min>0</lon_min>
    	<lon_max>20</lon_max>
    </zone>
    <datasets>
    	 <dats_id>626</dats_id>
    	 <dats_id>627</dats_id>
    </datasets>    
    <places>
    	<place_id>1433</place_id>
    	<place_id>885</place_id>
    	<place_id>4794</place_id>
    	<place_id>10468</place_id>
    	<place_id>939</place_id>
    </places>
  	<variables>
  		<var_id>332</var_id>
  		<var_id>481</var_id>
  		<!--var_id>232</var_id>
  		<var_id>443</var_id>
  		<var_id>52</var_id>
  		<var_id>279</var_id>
  		<var_id>205</var_id>
  		<var_id>235</var_id-->
  	</variables>
  </selection>
  <utilisateur>
    <utilisateur_email>guillaume.brissebrat@obs-mip.fr</utilisateur_email>
    <utilisateur_nom>Guillaume Brissebrat</utilisateur_nom>    
    <utilisateur_institute>Sedoo</utilisateur_institute>
  </utilisateur>
  <options>
    <format>ames</format>
    <format_version>1001</format_version>
    <compression>zip</compression>
    <valeurs_absentes>-9999.9</valeurs_absentes>
    <separateur>;</separateur>
    <valeur_flag>true</valeur_flag>
    <valeur_delta>true</valeur_delta>
  </options>
</requete>

=== sedoo/sedoo-portalgenerator/input/extraction/template-catalogue-extract/src/test/resources/test_na_2160.xml
<?xml version="1.0" encoding="UTF-8"?>
<requete xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://mistrals.sedoo.fr/extract/requete" xsi:schemaLocation="http://mistrals.sedoo.fr/extract/requete http://mistrals.sedoo.fr/extract/requete.xsd">
<projet>HyMeX</projet>
  <selection>
  	<periode>
    	<date_min>2011-11-01T00:00:00</date_min>
    	<date_max>2011-11-30T23:59:00</date_max>
    </periode>
    <zone>
    	<lat_min>40</lat_min>
    	<lat_max>45</lat_max>
    	<lon_min>0</lon_min>
    	<lon_max>5</lon_max>
    </zone>
    <datasets>
    	 <dats_id>626</dats_id>
    </datasets>    
    <places>
    	<place_id>16955</place_id>
    	<place_id>17829</place_id>
    	<place_id>885</place_id>
    </places>
  	<variables>
  		<var_id>332</var_id>
  		<var_id>52</var_id>
  		<var_id>336</var_id>
  		<var_id>279</var_id>
  		<var_id>205</var_id>
  		<var_id>232</var_id>
  		<!--var_id>481</var_id>
  		<var_id>232</var_id>
  		<var_id>443</var_id>
  		<var_id>279</var_id>
  		<var_id>205</var_id>
  		<var_id>235</var_id-->
  	</variables>
  </selection>
  <utilisateur>
    <utilisateur_email>guillaume.brissebrat@obs-mip.fr</utilisateur_email>
    <utilisateur_nom>Guillaume Brissebrat</utilisateur_nom>    
    <utilisateur_institute>Sedoo</utilisateur_institute>
  </utilisateur>
  <options>
    <format>ames</format>
    <format_version>2160</format_version>
    <compression>gzip</compression>
    <valeurs_absentes>-9999.9</valeurs_absentes>
    <separateur>;</separateur>
    <valeur_flag>false</valeur_flag>
    <valeur_delta>false</valeur_delta>
  </options>
</requete>

=== sedoo/sedoo-portalgenerator/template_catalogue/extract/requete.xml
<?xml version="1.0" encoding="UTF-8"?>
<requete xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://sedoo.fr/extract/requete" xsi:schemaLocation="http://sedoo.fr/extract/requete requete.xsd ">
	<projet>#MainProject</projet>
	<selection>
		<periode />
		<zone />
		<datasets />
		<places />
		<variables />
	</selection>
	<utilisateur>
		<utilisateur_email />
		<utilisateur_nom />
		<utilisateur_institute />
	</utilisateur>
	<options>
		<format />
		<format_version />
		<compression />
		<valeurs_absentes>-9999.9</valeurs_absentes>
		<separateur>;</separateur>
		<valeur_flag>false</valeur_flag>
		<valeur_delta>false</valeur_delta>
	</options>
</requete>
