=== sedoo/sedoo-portalgenerator/extracteur/xml/requete_files.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema elementFormDefault="qualified" targetNamespace="http://sedoo.fr/extract/requete_files" 
		xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
		xmlns:req="http://sedoo.fr/extract/requete_files">
    <xsd:element name="requete_files" type="req:requete_Type"></xsd:element>

    <xsd:complexType name="requete_Type">
    	<xsd:sequence>
    		<xsd:element name="projet" maxOccurs="1" minOccurs="1" type="xsd:string"></xsd:element>
    		<xsd:element name="utilisateur" type="req:utilisateur_Type"
    			maxOccurs="1" minOccurs="1">
    		</xsd:element>
    		<xsd:element name="compression" maxOccurs="1"
    			minOccurs="1">
    			<xsd:simpleType>
    				<xsd:restriction base="xsd:string">
    					<xsd:enumeration value="gzip"></xsd:enumeration>
    					<xsd:enumeration value="zip"></xsd:enumeration>
    					<xsd:enumeration value="none"></xsd:enumeration>
    				</xsd:restriction>
    			</xsd:simpleType>
    		</xsd:element>
    		<xsd:element name="selection">
    			<xsd:complexType>
    				<xsd:sequence>
    					<xsd:element name="datsId" type="xsd:int">
    					</xsd:element>
                        <xsd:element name="racine" type="xsd:string">
    					</xsd:element>
                        <xsd:element name="file" maxOccurs="unbounded"
                        	minOccurs="1">
                        	<xsd:simpleType>
                        		<xsd:restriction base="xsd:string">
                        			<xsd:minLength value="10"></xsd:minLength>
                        		</xsd:restriction>
                        	</xsd:simpleType>
                        </xsd:element>
                        
    				</xsd:sequence>
    			</xsd:complexType>
    		</xsd:element>
    	</xsd:sequence>
    </xsd:complexType>





    <xsd:complexType name="datasets_Type">
    	<xsd:sequence>
    		<xsd:element name="dats_id" type="xsd:int" maxOccurs="unbounded" minOccurs="0"></xsd:element>
    	</xsd:sequence>
    </xsd:complexType>
    
    

    <xsd:complexType name="utilisateur_Type">
    	<xsd:sequence>
    		<xsd:element name="utilisateur_email" type="xsd:string" maxOccurs="1" minOccurs="1"></xsd:element>
    		<xsd:element name="utilisateur_nom" type="xsd:string" maxOccurs="1" minOccurs="1"></xsd:element>
    		<xsd:element name="utilisateur_institute" type="xsd:string" maxOccurs="1" minOccurs="0"></xsd:element>
    	</xsd:sequence>
    </xsd:complexType>
    


</xsd:schema>

=== sedoo/sedoo-portalgenerator/template_catalogue/extract/requete_files.xml
<?xml version="1.0" encoding="UTF-8"?>
<requete_files xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://mistrals.sedoo.fr/extract/requete_files" xsi:schemaLocation="http://mistrals.sedoo.fr/extract/requete_files http://mistrals.sedoo.fr/extract/requete_files.xsd">
<projet>MISTRALS</projet>
	<utilisateur>
		<utilisateur_email />
		<utilisateur_nom />
		<utilisateur_institute />
	</utilisateur>
	<compression>zip</compression>
	<selection>
		<datsId />
		<racine />
	</selection>

</requete_files>

=== sedoo/sedoo-portalgenerator/input/extraction/template-catalogue-extract/src/test/resources/test_public.xml
<?xml version="1.0" encoding="UTF-8"?>
<requete_files xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://mistrals.sedoo.fr/extract/requete_files" xsi:schemaLocation="http://mistrals.sedoo.fr/extract/requete_files http://mistrals.sedoo.fr/extract/requete_files.xsd">
<projet>HyMeX</projet>
	<utilisateur>
		<utilisateur_email>guillaume.brissebrat@obs-mip.fr</utilisateur_email>
		<utilisateur_nom>guest</utilisateur_nom>
		<utilisateur_institute></utilisateur_institute>
	</utilisateur>
	<compression>zip</compression>
	<selection>
		<datsId>594</datsId>
		<racine>/export1/mistrals/hymex_data/gts/SYNOP</racine>
		<file>/export1/mistrals/hymex_data/gts/SYNOP/0_Documentation</file>
		<file>/export1/mistrals/hymex_data/gts/SYNOP/2010/05/SYN_100501.asc.gz</file>
	</selection>

</requete_files>

=== sedoo/sedoo-portalgenerator/input/extraction/template-catalogue-extract/src/test/resources/test_fichiers_gros.xml
<?xml version="1.0" encoding="UTF-8"?>
<requete_files xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://mistrals.sedoo.fr/extract/requete_files" xsi:schemaLocation="http://mistrals.sedoo.fr/extract/requete_files http://mistrals.sedoo.fr/extract/requete_files.xsd">
<projet>HyMeX</projet>
	<utilisateur>
		<utilisateur_email>guillaume.brissebrat@obs-mip.fr</utilisateur_email>
		<utilisateur_nom>Guillaume Brissebrat</utilisateur_nom>
		<utilisateur_institute>Sedoo</utilisateur_institute>
	</utilisateur>
	<compression>zip</compression>
	<selection>
		<datsId>627</datsId>
		<racine>/export1/mistrals/hymex_data/bdclim/hourly</racine>
		<file>/export1/mistrals/hymex_data/bdclim/hourly/0_Documentation</file>
		<file>/export1/mistrals/hymex_data/bdclim/hourly/1995</file>
		<file>/export1/mistrals/hymex_data/bdclim/hourly/2012</file>
		<file>/export1/mistrals/hymex_data/bdclim/hourly/2005</file>
		<file>/export1/mistrals/hymex_data/bdclim/hourly/1994/01</file>
		<file>/export1/mistrals/hymex_data/bdclim/hourly/1993/01</file>
	</selection>

</requete_files>
